// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWcxm6jV9APQZjJ3fX3I-qUX6zy-zX-wA',
    appId: '1:386187450353:web:77905e3045cadc59e45650',
    messagingSenderId: '386187450353',
    projectId: 'login-signup-92d36',
    authDomain: 'login-signup-92d36.firebaseapp.com',
    storageBucket: 'login-signup-92d36.firebasestorage.app',
    measurementId: 'G-LQKCQN0VGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuTUl6jSBrhmnaOhcPSfPz-d_dNgVUx_k',
    appId: '1:386187450353:android:a8d6a36407719d99e45650',
    messagingSenderId: '386187450353',
    projectId: 'login-signup-92d36',
    storageBucket: 'login-signup-92d36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx7LHcpg2EVws3toqed78mglGVZE_5b5I',
    appId: '1:386187450353:ios:5c579b851b84d429e45650',
    messagingSenderId: '386187450353',
    projectId: 'login-signup-92d36',
    storageBucket: 'login-signup-92d36.firebasestorage.app',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx7LHcpg2EVws3toqed78mglGVZE_5b5I',
    appId: '1:386187450353:ios:5c579b851b84d429e45650',
    messagingSenderId: '386187450353',
    projectId: 'login-signup-92d36',
    storageBucket: 'login-signup-92d36.firebasestorage.app',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWcxm6jV9APQZjJ3fX3I-qUX6zy-zX-wA',
    appId: '1:386187450353:web:6a5171153e960ba3e45650',
    messagingSenderId: '386187450353',
    projectId: 'login-signup-92d36',
    authDomain: 'login-signup-92d36.firebaseapp.com',
    storageBucket: 'login-signup-92d36.firebasestorage.app',
    measurementId: 'G-0846YPSYHY',
  );

}